### ISSUE TITLE
Adding a non-existent tag produces confusing end-user errors

### ISSUE THREAD

**Issue by juledwar** [anchore/anchore-engine#150] opened 2019-02-28 00:56 UTC
E.g.
```
[service:catalog] 2019-02-27 23:37:14+0000 [-] Exception: could not get manifest/digest for image (docker.io/library/elasticsearch:latest) from registry (https://index.docker.io) - error: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo inspect --raw --tls-verify=false  docker://docker.io/library/elasticsearch:latest, rc=1, stdout=None, stderr=b'time="2019-02-27T23:37:14Z" level=fatal msg="Error reading manifest latest in docker.io/library/elasticsearch: manifest unknown: manifest unknown" \n'
```

The client sees a 400 (BAD_REQUEST) response to the `image add`. However it's not discernible from the error that the tag specified does not actually exist.

**Comment by nurmi** [comment] 2019-03-28 21:47
hi @juledwar!

We spoke a bit about this on another channel, but I wanted to follow up here: in the original post, that image (docker.io/library/elasticsearch:latest) doesn't exist, and the behavior of the system from the API/user perspective is currently:

```
[root@tele anchore-engine]# anchore-cli image add docker.io/library/elasticsearch:latest
Error: cannot fetch image digest/manifest from registry
HTTP Code: 400
Detail: {u'raw_exception_message': u'could not get manifest/digest for image (docker.io/library/elasticsearch:latest) from registry (https://index.docker.io) - error: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  inspect --raw --tls-verify=true --creds "${SKOPUSER}":"${SKOPPASS}" docker://docker.io/library/elasticsearch:latest, rc=1, stdout=None, stderr=b\'time="2019-03-28T21:40:52Z" level=fatal msg="Error reading manifest latest in docker.io/library/elasticsearch: manifest unknown: manifest unknown" \\n\''}

[root@tele anchore-engine]# anchore-cli --json image add docker.io/library/elasticsearch:latest
{
    "detail": {
        "raw_exception_message": "could not get manifest/digest for image (docker.io/library/elasticsearch:latest) from registry (https://index.docker.io) - error: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  inspect --raw --tls-verify=true --creds \"${SKOPUSER}\":\"${SKOPPASS}\" docker://docker.io/library/elasticsearch:latest, rc=1, stdout=None, stderr=b'time=\"2019-03-28T21:40:58Z\" level=fatal msg=\"Error reading manifest latest in docker.io/library/elasticsearch: manifest unknown: manifest unknown\" \\n'"
    }, 
    "httpcode": 400, 
    "message": "cannot fetch image digest/manifest from registry"
}
```

While there are several conditions that will generate a 400 with the general error 'cannot fetch image digest/manifest from registry', the 'detail' section has more specific information in it about the nature of the core issue (registry access auth issue,  manifest unknown, timedout, etc) from the backend operation.  

Can please you provide some more insight into the ask / use case here?

**Comment by juledwar** [comment] 2019-03-28 23:32
Hi there - yes, sorry, the elasticsearch example is bad!

The use case is for clients using the API, not the CLI. The 400 returned doesn't tell me whether the request was bad, or the upstream service had a blip. In the latter case it should probably return SERVICE_UNAVAILABLE (503) because the request is not inherently bad.

Hopefully this makes more sense!

**Comment by nurmi** [comment] 2019-03-28 23:52
hi @juledwar,

That does help to clarify, thanks!  The reason that I'd hesitate to use the 500 codes is that generally I would think that the 500 would indicate a service unavailable failure in the anchore service itself, which in these cases (where the registries are not accessible) the issue is really about the resource being asked for (an image fetch) rather than the anchore service (which is operating normally). 

There are cases like this where I completely agree that it is difficult to find the right error to correctly explain the situation, limited by the HTTP codes and their meanings, but think we should be careful not to introduce an error code that could be misunderstood by other clients (503 for example one could understand that to mean that the service is unavailable - it isn't and many other image tags/registries/etc could be working just fine - the condition here is potentially strictly related to the specific client request details, which is why we chose the 400 series for this particular failure, with the details about why in the message detail). 

Still difficult as there isn't a clear correct choice here, but at a high level we've reserved the 500 series of http codes to be strictly related to internal service failures, and 400s to be about failures related to request specific details and if possible I'd like to keep that model.

Perhaps an alternate approach would be to make the detail more programatically usable so that different 'cannot fetch the manifest' cases can be handled in different ways depending on the exact nature of the failure.

**Comment by juledwar** [comment] 2019-03-29 00:02
Hi

I would argue that if the registry is inaccessible then the service is unavailable as Anchore cannot work without it.

The description for 503 is:
```
The server is currently unable to handle the request due to a temporary overload or scheduled maintenance, which will likely be alleviated after some delay.
```
I can understand why you might not want to use this as it's not necessarily an "overload or maintenance", but equally 400 is wrong as there is nothing intrinsically bad with the request - the server simply cannot complete the request at this time due to a fault, which implies 5xx to me. Maybe 504? (gateway timeout)

https://httpstatuses.com/

Cheers.

**Comment by nurmi** [comment] 2019-03-29 01:27
I understand the position, but the part of the 50X that makes those cods not fit the case is that in anchore's case, there isn't necessarily just 'a' registry (commonly there are many registry credentials in place and images being pulled in from multiple registry sources).  For the specific case being referenced (one of the registries, which is chosen based on input from the request, is flapping, or that particular tag isn't available) the system could be handling other registries or even images from the same with success.  The current http code model in the engine uses 500s to indicate more anchore service oriented issues (generally unrelated to the specifics of the request) which is fundamentally why I'd hesitate in this case to switch.

I'm curious if you had (in parallel) any thoughts on my proposal, as I think a good solution for these types of ambiguities (where an HTTP code isn't quite right or expressive enough) can be found in extending the information in the error envelope itself, in order to allow for more detailed/differentiated client handling based on the specific error condition.

**Comment by juledwar** [comment] 2019-03-29 01:47
Fair comments Dan. At the end of the day as long as we can distinguish via the API what the problem is, then it's all good. Obviously trying to be as RFC compliant as possible is beneficial.


Thank you for looking into this!

________________________________

**Comment by nurmi** [comment] 2019-03-29 23:00
Hi @juledwar - appreciate you working with us on this (and other) topics!  I'll make some proposals on more structured error details here for review after reviewing the codepaths and making sure we can cleanly differentiate some important registry access failure cases.

**Comment by nurmi** [comment] 2019-04-11 18:03
HI @juledwar - I'm following up with a prototype proposal here - I've implemented a structure in anchore that allows anchore error codes to be made accessible through to the API results, where an example follows which I believe satisfies the use case discussed for review - after some testing we'll commit this feature to master as well.  Looking forward to feedback!

```
anchore@f03a1fb480e6:~$ curl -u admin:foobar http://localhost:8228/v1/system/error_codes
[
  {
    "description": "The registry has reported permission denied for the requested registry resource",
    "name": "REGISTRY_PERMISSION_DENIED"
  },
  {
    "description": "The requested image (tag, digest) cannot be found in the requested registry",
    "name": "REGISTRY_IMAGE_NOT_FOUND"
  },
  {
    "description": "The registry is not accessible on the network from the anchore engine service",
    "name": "REGISTRY_NOT_ACCESSIBLE"
  },
  {
    "description": "Anchore cannot access the specified registry as supporting the v2 registry API",
    "name": "REGISTRY_NOT_SUPPORTED"
  },
  {
    "description": "The skopeo command has failed due to an error that is not explicitly handled, see the command output/error for more information",
    "name": "SKOPEO_UNKNOWN_ERROR"
  },
  {
    "description": "An unknown error has occurred, please consult the anchore service logs for more information",
    "name": "UNKNOWN"
  }
]
anchore@f03a1fb480e6:~$ anchore-cli --json image add 192.168.1.10/node:latest
{
    "detail": {
        "error_codes": [
            "REGISTRY_NOT_ACCESSIBLE"
        ],
        "raw_exception_message": "Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  inspect --raw --tls-verify=false  docker://192.168.1.10/node:latest, rc=1, stdout=None, stderr=b'time=\"2019-04-11T17:58:39Z\" level=fatal msg=\"pinging docker registry returned: Get http://192.168.1.10/v2/: dial tcp 192.168.1.10:80: connect: no route to host\" \\n', error_code=REGISTRY_NOT_ACCESSIBLE"
    },
    "httpcode": 400,
    "message": "cannot fetch image digest/manifest from registry"
}
anchore@f03a1fb480e6:~$ anchore-cli --json image add 192.168.1.3/node:latest
{
    "detail": {
        "error_codes": [
            "REGISTRY_NOT_ACCESSIBLE"
        ],
        "raw_exception_message": "Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  inspect --raw --tls-verify=false  docker://192.168.1.3/node:latest, rc=1, stdout=None, stderr=b'time=\"2019-04-11T17:58:52Z\" level=fatal msg=\"pinging docker registry returned: Get http://192.168.1.3/v2/: dial tcp 192.168.1.3:80: connect: connection refused\" \\n', error_code=REGISTRY_NOT_ACCESSIBLE"
    },
    "httpcode": 400,
    "message": "cannot fetch image digest/manifest from registry"
}
anchore@f03a1fb480e6:~$ anchore-cli --json image add docker.io/alpine:tag_that_doesnt_exist
{
    "detail": {
        "error_codes": [
            "REGISTRY_IMAGE_NOT_FOUND"
        ],
        "raw_exception_message": "Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  inspect --raw --tls-verify=false  docker://docker.io/library/alpine:tag_that_doesnt_exist, rc=1, stdout=None, stderr=b'time=\"2019-04-11T17:59:12Z\" level=fatal msg=\"Error reading manifest tag_that_doesnt_exist in docker.io/library/alpine: manifest unknown: manifest unknown\" \\n', error_code=REGISTRY_IMAGE_NOT_FOUND"
    },
    "httpcode": 400,
    "message": "cannot fetch image digest/manifest from registry"
}
anchore@f03a1fb480e6:~$ anchore-cli --json image add docker.io/some/private/repo:latest
{
    "detail": {
        "error_codes": [
            "REGISTRY_PERMISSION_DENIED"
        ],
        "raw_exception_message": "Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  inspect --raw --tls-verify=false  docker://docker.io/some/private/repo:latest, rc=1, stdout=None, stderr=b'time=\"2019-04-11T17:59:26Z\" level=fatal msg=\"Error reading manifest latest in docker.io/some/private/repo: errors:\\ndenied: requested access to the resource is denied\\nunauthorized: authentication required\\n\" \\n', error_code=REGISTRY_PERMISSION_DENIED"
    },
    "httpcode": 400,
    "message": "cannot fetch image digest/manifest from registry"
}
```

**Comment by juledwar** [comment] 2019-04-11 23:31
This is great, would be excellent extra feedback on error conditions. Thanks for looking into it!

**Comment by 0xDEC0DE** [comment] 2019-04-11 23:44
I would like to point out that HTTP 422 is designated as the response code for "syntactically valid, yet still bad" requests:

https://httpstatuses.com/422

**Comment by nurmi** [comment] 2019-04-12 21:55
Thanks @juledwar , @0xDEC0DE - I've merged the proposed method (error_codes) into master - I'll close out this ticket, but for future discussions on the usage of HTTP codes in the anchore API, lets open a new topic as this would be a more central, broader discussion for the mapping of semantics to http codes for the anchore API in general (beyond the specific use case in this ticket, which the error_codes solution should remedy!)

**Closed by nurmi** 2019-04-12 21:55 UTC

**Comment by mohamedoul** [comment] 2019-05-20 15:04
The solution that I have found is :+1: 
$ sudo usermod -aG docker $USER
 and it works for me

**Comment by mohitmehral** [comment] 2021-08-23 15:58
Any lead on this I am also getting this error

```
[service:catalog] 2021-08-23 15:53:29+0000 [-]
[service:catalog] 2021-08-23 15:53:29+0000 [-] During handling of the above exception, another exception occurred:
[service:catalog] 2021-08-23 15:53:29+0000 [-]
[service:catalog] 2021-08-23 15:53:29+0000 [-] Traceback (most recent call last):
[service:catalog] 2021-08-23 15:53:29+0000 [-]   File "/usr/local/lib/python3.8/site-packages/anchore_engine/services/catalog/catalog_impl.py", line 659, in image
[service:catalog] 2021-08-23 15:53:29+0000 [-]     raise err
[service:catalog] 2021-08-23 15:53:29+0000 [-]   File "/usr/local/lib/python3.8/site-packages/anchore_engine/services/catalog/catalog_impl.py", line 576, in image
[service:catalog] 2021-08-23 15:53:29+0000 [-]     raise err
[service:catalog] 2021-08-23 15:53:29+0000 [-]   File "/usr/local/lib/python3.8/site-packages/anchore_engine/services/catalog/catalog_impl.py", line 555, in image
[service:catalog] 2021-08-23 15:53:29+0000 [-]     image_info = anchore_engine.common.images.get_image_info(
[service:catalog] 2021-08-23 15:53:29+0000 [-]   File "/usr/local/lib/python3.8/site-packages/anchore_engine/common/images.py", line 66, in get_image_info
[service:catalog] 2021-08-23 15:53:29+0000 [-]     raise anchore_engine.common.helpers.make_anchore_exception(
[service:catalog] 2021-08-23 15:53:29+0000 [-] Exception: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo   inspect --raw --tls-verify=true --creds "${SKOPUSER}":"${SKOPPASS}" docker://000186693631.dkr.ecr.eu-central-1.amazonaws.com/anchore-scan:manifest, rc=1, stdout=None, stderr=b'time="2021-08-23T15:53:29Z" level=fatal msg="Error parsing image name \\"docker://000186693631.dkr.ecr.eu-central-1.amazonaws.com/anchore-scan:manifest\\": Error reading manifest manifest in 000186693631.dkr.ecr.eu-central-1.amazonaws.com/anchore-scan: manifest unknown: Requested image not found"\n', error_code=REGISTRY_IMAGE_NOT_FOUND
```
