### ISSUE TITLE
low performance on image evaluation

### ISSUE THREAD

**Issue by armstrongli** [anchore/anchore-engine#81] opened 2018-08-13 05:35 UTC
**Is this a request for help?**:
* No
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
* bug report

**Version of Anchore Engine and Anchore CLI if applicable**:
All the versions of anchore
 
**What happened**:
The kubernetes image policy is very low performance

**What did you expect to happen**:
The evaluation has been done by calling the eval, and a evaluation result is stored in table *policy_eval* . The evaluation should be extremely fast as it is only a one-row query. 

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**:

**How to reproduce the issue**:

**Anything else we need to know**:
The call stack of the kubernetes webhook is:
* anchore_engine/services/kubernetes_webhook/api/controllers/default_controller.py
   * `imagepolicywebhook(bodycontent)`
   * result = catalog.get_eval_latest(request_user_auth, tag=fulltag, imageDigest=imageDigest, policyId=requestPolicyId)
* anchore_engine/clients/catalog.py
   * get_eval_latest(userId, policyId=None, imageDigest=None, tag=None, evalId=None)
   * eval_records = get_evals(userId, policyId=policyId, imageDigest=imageDigest, tag=tag, evalId=evalId, newest_only=True)
   * get_evals(userId, policyId=None, imageDigest=None, tag=None, evalId=None, newest_only=False)
   * ret = http.anchy_get(url, params=params, auth=auth, headers=headers, verify=localconfig['internal_ssl_verify'])
* anchore_engine/services/catalog/api/controllers/policy_evaluations.py
   * get_evals(policyId=None, imageDigest=None, tag=None, evalId=None, newest_only=False)
   * **list_evals_impl(session, userId=user_id, policyId=policyId, imageDigest=imageDigest, tag=tag, evalId=evalId)** . Down here, all the calls are going through the same logic as the `newest_only` option is dropped and not used anywhere.
   * list_evals_impl(dbsession, userId, policyId=None, imageDigest=None, tag=None, evalId=None, newest_only=False)
   * rc = catalog_impl.perform_policy_evaluation(userId, imageDigest, dbsession, evaltag=evaltag, policyId=policyId)

The whole stack show that all the requests are hitting the policy engine and does the whole evaluation every time when there's a evaluation call.

**Comment by armstrongli** [comment] 2018-08-13 05:38
PR for this issue on performance fix: https://github.com/anchore/anchore-engine/pull/82

**Comment by a-zen** [comment] 2018-08-14 09:14
I'm having the same issue. Analyzing an image is fast enough but doing an evalute takes 1 - 2 minutes, even though I currently only have two images analyzed.

**Comment by zhill** [comment] 2019-01-11 05:34
This has been addressed in release v0.3.1. The system now will only evaluate a policy again if the image, bundle, or feeds have changed. I'll leave this open for feedback on the changes.

**Comment by zhill** [comment] 2019-11-19 17:00
Close this due to inactivity and age. Please re-open or file a new issue if the problem is not resolved.

**Closed by zhill** 2019-11-19 17:00 UTC
