### ISSUE TITLE
Health Check failure when using SSL

### ISSUE THREAD

**Issue by Ringeltier** [anchore/anchore-engine#238] opened 2019-07-24 12:45 UTC
**Is this a request for help?**:no

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:0.4.1

 
**What happened**:When using SSL on engine-api the healthcheck always show "unhealthy"

**What did you expect to happen**:That it shows healthy

**How to reproduce the issue**:Use SSL configuration for engine-api. The healthcheck checks for http://localhost:8228/health and not for https://localhost:8228/health .

**Anything else we need to know**:
When you are adding a Dockerfile and overwrite the healthcheck it works!

**Comment by nurmi** [comment] 2019-07-24 18:37
Hi @Ringeltier - 

Thank you for the report - I wanted to add that there are also ways to override the healthcheck operation without the need to rebuild container (in with docker, docker-compose, etc).  

https://docs.docker.com/compose/compose-file/compose-file-v2/#healthcheck https://stackoverflow.com/questions/53772248/how-to-modify-docker-health-check-without-rebuilding-image

I'd be interested if you had an example of a container where it could be configured either with TLS or not (and includes a healthcheck in it's dockerfile) which has implemented a good solution to this problem, always looking for best practices but in this case it isn't clear to me (there are many solutions, but all with tradeoffs :)

**Comment by Ringeltier** [comment] 2019-07-25 05:47
Hello @nurmi -

Thank you for your quick answer. I will try it to overwrite it within the docker-compose and will report the result to you. 

After this i will post my current Dockerfile which is fixing the bug
`
FROM anchore/anchore-engine:v0.4.1

HEALTHCHECK --start-period=20s \
    CMD curl -f --insecure https://localhost:8228/health || exit 1
`

**Comment by Ringeltier** [comment] 2019-07-25 07:14
Hello @nurmi -

I edited the docker-compose.yaml and added the healthcheck within the engine-api. And it is working like a charm.

docker-compose.yaml
```diff
engine-api:
    image: anchore/anchore-engine:v0.4.1
    depends_on:
    - anchore-db
    - engine-catalog
    restart: always
    ports:
    - "443:8228"
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    volumes:
    - /var/anchore/config/config.yaml:/config/config.yaml:z
    - /var/anchore/config/ssl/fullchain.pem:/config/ssl/fullchain.pem
    - /var/anchore/config/ssl/privkey.pem:/config/ssl/privkey.pem
    - /var/anchore/config/ssl/chain.pem:/config/ssl/chain.pem
+   healthcheck:
+     test: ["CMD-SHELL", "curl -f --insecure https://localhost:8228/health || exit 1"]
    environment:
    - ANCHORE_ENDPOINT_HOSTNAME=engine-api
    - ANCHORE_DB_HOST=anchore-db
    - ANCHORE_DB_PASSWORD=mysecretpassword
    command: ["anchore-manager", "service", "start", "apiext"]
```

Result:
```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                    PORTS                     NAMES
d6fcf8c3c305        anchore/anchore-engine:v0.4.1   "/docker-entrypoint.…"   9 minutes ago       Up 9 minutes (healthy)    0.0.0.0:443->8228/tcp     anchore_engine-api_1
49910357bb0a        anchore/anchore-engine:v0.4.1   "/docker-entrypoint.…"   12 minutes ago      Up 12 minutes (healthy)   8228/tcp                  anchore_engine-simpleq_1
c1f2b06ecd5d        anchore/anchore-engine:v0.4.1   "/docker-entrypoint.…"   12 minutes ago      Up 12 minutes (healthy)   8228/tcp                  anchore_engine-policy-engine_1
db8f51808f0a        anchore/anchore-engine:v0.4.1   "/docker-entrypoint.…"   12 minutes ago      Up 12 minutes (healthy)   8228/tcp                  anchore_engine-analyzer_1
3a8f5a563a41        anchore/anchore-engine:v0.4.1   "/docker-entrypoint.…"   12 minutes ago      Up 12 minutes (healthy)   8228/tcp                  anchore_engine-catalog_1
c21f8b384f09        postgres:9                      "docker-entrypoint.s…"   12 minutes ago      Up 12 minutes             5432/tcp                  anchore_anchore-db_1
```

**Comment by zhill** [comment] 2019-09-17 04:47
Closing this because it seems resolved and was not a bug, just a configuration question. If any follow-up is needed please reopen.

**Closed by zhill** 2019-09-17 04:47 UTC
