### ISSUE TITLE
Unable to add image using anchore cli which is hosted on azure container registry

### ISSUE THREAD

**Issue by praneethr** [anchore/anchore-engine#34] opened 2018-04-06 17:28 UTC
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG REPORT

**Steps to Install Anchore suite**
Created Postgres PAAS on Azure
Configured Postgres DB on config yamls
Installed anchore core engine and analyzer as pods on k8s cluster.

Installed Anchore CLI on k8 cluster master node.

```
anchore-cli system status
Service kubernetes_webhook (dockerhostid-xyz, http://localhost:8338): up
Service analyzer (dockerhostid-xyz, N/A): up
Service policy_engine (dockerhostid-xyz, http://localhost:8087): up
Service catalog (dockerhostid-xyz, http://localhost:8082): up
Service apiext (dockerhostid-xyz, http://localhost:8228): up
Service simplequeue (dockerhostid-xyz, http://localhost:8083): up

Engine Status: all_up
```

```
anchore-cli --version
anchore-cli, version 0.1.9
```

I added a azure container registry 
```
anchore-cli registry list
Registry                           Type             User
buycscregstg.azurecr.io            docker_v2       <<user>>
```

When i try to add image using cli.. got below error:

```
anchore-cli image add buycscregstg.azurecr.io/buy/centos7:7.4
Error: image cannot be found/fetched from registry
HTTP Code: 404

```
In Anchore core engine logs:

[service:kubernetes-webhook] 2018-04-06 17:24:45+0000 [-] "127.0.0.1" - - [06/Apr/2018:17:24:44 +0000] "GET /v1/status HTTP/1.1" 200 61 "-" "python-requests/2.17.3"
[service:policy-engine] 2018-04-06 17:24:45+0000 [-] "127.0.0.1" - - [06/Apr/2018:17:24:44 +0000] "GET /v1/status HTTP/1.1" 200 61 "-" "python-requests/2.17.3"
[service:api] 2018-04-06 17:24:45+0000 [-] "127.0.0.1" - - [06/Apr/2018:17:24:44 +0000] "GET /v1/status HTTP/1.1" 200 110 "-" "python-requests/2.17.3"
[service:simplequeue] 2018-04-06 17:24:45+0000 [-] "127.0.0.1" - - [06/Apr/2018:17:24:44 +0000] "GET /v1/status HTTP/1.1" 200 404 "-" "python-requests/2.17.3"
[service:catalog] 2018-04-06 17:24:47+0000 [-] "127.0.0.1" - - [06/Apr/2018:17:24:46 +0000] "GET /v1/system/services/simplequeue HTTP/1.1" 200 721 "-" "python-requests/2.17.3"
[service:simplequeue] 2018-04-06 17:24:47+0000 [-] "127.0.0.1" - - [06/Apr/2018:17:24:46 +0000] "GET /v1/queues/policy_eval/qlen HTTP/1.1" 200 4 "-" "python-requests/2.17.3"
[service:simplequeue] 2018-04-06 17:24:47+0000 [-] "127.0.0.1" - - [06/Apr/2018:17:24:46 +0000] "GET /v1/queues/tag_update/qlen HTTP/1.1" 200 4 "-" "python-requests/2.17.3"
[service:simplequeue] 2018-04-06 17:24:47+0000 [-] "127.0.0.1" - - [06/Apr/2018:17:24:46 +0000] "GET /v1/queues/vuln_update/qlen HTTP/1.1" 200 4 "-" "python-requests/2.17.3"
[service:simplequeue] 2018-04-06 17:24:47+0000 [-] "127.0.0.1" - - [06/Apr/2018:17:24:46 +0000] "GET /v1/queues/repo_update/qlen HTTP/1.1" 200 4 "-" "python-requests/2.17.3"
[service:simplequeue] 2018-04-06 17:24:47+0000 [-] "127.0.0.1" - - [06/Apr/2018:17:24:46 +0000] "GET /v1/queues/analysis_update/qlen HTTP/1.1" 200 4 "-" "python-requests/2.17.3"
[service:simplequeue] 2018-04-06 17:24:47+0000 [-] "127.0.0.1" - - [06/Apr/2018:17:24:46 +0000] "GET /v1/queues/error_event/qlen HTTP/1.1" 200 4 "-" "python-requests/2.17.3"
[service:api] 2018-04-06 17:24:53+0000 [-] "10.247.5.201" - - [06/Apr/2018:17:24:52 +0000] "GET /v1 HTTP/1.1" 200 - "-" "python-requests/2.17.3"
**[service:api] 2018-04-06 17:24:53+0000 [-] "10.247.5.201" - - [06/Apr/2018:17:24:53 +0000] "POST /v1/images?autosubscribe=True HTTP/1.1" 404 189 "-" "python-requests/2.17.3"
[service:catalog] 2018-04-06 17:24:53+0000 [_GenericHTTPChannelProtocol,61,127.0.0.1] [PoolThread-twisted.internet.reactor-0] [anchore_engine.auth.skopeo_wrapper/get_image_manifest_skopeo()] [ERROR] command failed with exception - command failed: cmd=/bin/sh -c skopeo inspect --raw --tls-verify=true --creds "${SKOPUSER}":"${SKOPPASS}" docker://buycscregstg.azurecr.io/buy/centos7:7.4 exitcode=1 stdout= stderr=time="2018-04-06T17:24:53Z" level=fatal msg="unauthorized: authentication required"
[service:catalog] 2018-04-06 17:24:53+0000 [_GenericHTTPChannelProtocol,61,127.0.0.1] [PoolThread-twisted.internet.reactor-0] [anchore_engine.auth.skopeo_wrapper/get_image_manifest_skopeo()] [WARN] CMD failed - exception: command failed: cmd=/bin/sh -c skopeo inspect --raw --tls-verify=true --creds "${SKOPUSER}":"${SKOPPASS}" docker://buycscregstg.azurecr.io/buy/centos7:7.4 exitcode=1 stdout= stderr=time="2018-04-06T17:24:53Z" level=fatal msg="unauthorized: authentication required"
[service:catalog] 2018-04-06 17:24:53+0000 [_GenericHTTPChannelProtocol,61,127.0.0.1] [PoolThread-twisted.internet.reactor-0] [anchore_engine.auth.docker_registry/get_image_manifest()] [ERROR] could not fetch manifest/digest: no digest/manifest from skopeo
[service:catalog] 2018-04-06 17:24:53+0000 [_GenericHTTPChannelProtocol,61,127.0.0.1] [PoolThread-twisted.internet.reactor-0] [anchore_engine.auth.docker_registry/get_image_manifest()] [ERROR] could not get manifest/digest for image using any auth method: (7.4):**
[service:catalog] 2018-04-06 17:24:53+0000 [-] "127.0.0.1" - - [06/Apr/2018:17:24:53 +0000] "POST /v1/image?tag=buycscregstg.azurecr.io/buy/centos7:7.4 HTTP/1.1" 404 189 "-" "python-requests/2.17.3"
[service:kubernetes-webhook] 2018-04-06 17:25:04+0000 [-] "127.0.0.1" - - [06/Apr/2018:17:25:03 +0000] "GET /v1/status HTTP/1.1" 200 61 "-" "python-requests/2.17.3"
[service:policy-engine] 2018-04-06 17:25:04+0000 [-] "127.0.0.1" - - [06/Apr/2018:17:25:03 +0000] "GET /v1/status HTTP/1.1" 200 61 "-" "python-requests/2.17.3"

**Comment by zhill** [comment] 2018-04-06 18:16
Hi @praneethr, this is a known issue (see #18 ) due to an upstream dependency. I'd like to close this issue as a duplicate of 18, so please add a comment in that ticket that you too are impacted so we only have to track in one issue. Given that this is impacting more folks, we'll see what kind of workaround we can do regarding a custom skopeo build and will update that ticket with info. Thanks!

**Comment by zhill** [comment] 2018-05-17 20:17
The latest release of Skopeo now has Azure support, so if you want to pull the latest version into a custom container based on the anchore/anchore-engine:v0.2.1 container that should be a sufficient workaround to get Azure support until we release the next engine version container with the updated tool in it.

**Comment by nurmi** [comment] 2018-06-09 00:48
Anchore engine version 0.2.2 includes skopeo version 0.1.29, which should resolve this incompatibility!

**Closed by nurmi** 2018-06-09 00:48 UTC
