### ISSUE TITLE
anchore-engine in Docker Swarm gives zombie containers

### ISSUE THREAD

**Issue by bjwschaap** [anchore/anchore-engine#97] opened 2018-10-04 09:59 UTC
I've deployed `anchore-engine` to a Docker Swarm cluster using the provided `docker-compose.yml` in the `master` branch of this repo. This deploys a stack with 2 containers as expected (database and engine).

When redeploying the stack Docker Swarm will first issue a SIGTERM to the running engine container, wait for it to stop, and when stopped start a new container. If the container does not stop within a specific time (10 seconds), it will issue a SIGKILL.

Because `shell` form of `CMD` is used, the `anchore-engine` process is started from `/bin/sh -c`. Normally this is not a problem, however `anchore-engine` spawns subprocesses, and because of the main process being in a shell, the SIGTERM and SIGKILL signals are not properly propagated into the child processes. This causes `anchore-engine` zombie containers to be left on the Docker host, which can only be removed by restarting the Docker daemon.

The `anchore-engine` Dockerfiles should be fixed to:
- use `exec` form instead of `shell` form
- add an `init` like process that properly propagates the system SIGTERM and SIGKILL signals (e.g. `tini`)

For more background info see:
https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/
and:
https://docs.docker.com/engine/reference/builder/#cmd

## Steps to Reproduce:
1. use docker-compose installation instructions from README
2. instead of `docker-compose up` use `docker stack deploy`
3. use `docker service scale` to first set `anchore-engine` to 0 replicas
4. and then scale `anchore-engine` back to 1 replica
5. with `docker service ls` it is observed that `anchore-engine` now has `2/1` in the replica column

I will make a PR with suggested changes.

**Comment by bjwschaap** [comment] 2018-10-04 10:10
An alternative way to 'fix' the issue would be to migratie the docker-compose file to version `3.7`, which provides a way to let Docker 'inject' a `tini`-like process manager instead of handling it inside the container:

https://docs.docker.com/compose/compose-file/#init

However this might break using the compose file for certain users restricted to using older Docker versions.

**Comment by nurmi** [comment] 2018-10-13 00:05
@bjwschaap - thank you for the detailed report and PR example solution!  As we're porting anchore-engine to Python3, there are still some modifications that we've been making to the build/bootstrap/service start model that are ongoing, and we're going to take into consideration your work and suggestions.  We'll follow-up here on progress!

**Comment by zhill** [comment] 2019-10-14 18:05
I'm closing this due to the age, but if the problem is still present please re-open. We are currently using the exec form of CMD in the Dockerfile.

**Closed by zhill** 2019-10-14 18:05 UTC
