### ISSUE TITLE
Analyzing Images

### ISSUE THREAD

**Issue by tmaheedhar2** [anchore/anchore-engine#1038] opened 2021-05-18 12:21 UTC
**Is this a request for help?**:

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

**Version of Anchore Engine and Anchore CLI if applicable**:

**What happened**:

**What did you expect to happen**:

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**:

**How to reproduce the issue**:

**Anything else we need to know**:

**Comment by tmaheedhar2** [comment] 2021-05-18 12:22
anchore-cli image add docker.io/library/spe:0.1      
Error: cannot fetch image digest/manifest from registry
HTTP Code: 400
Detail: {u'raw_exception_message': u'could not get manifest/digest for image (docker.io/library/spe:0.1) from registry (https://index.docker.io) - error: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  inspect --raw --tls-verify=false  docker://docker.io/library/spe:0.1, rc=1, stdout=None, stderr=b\'time="2021-05-18T12:16:42Z" level=fatal msg="Error reading manifest 0.1 in docker.io/library/spe: errors:\\ndenied: requested access to the resource is denied\\nunauthorized: authentication required\\n" \\n\''}

**Comment by Vijay-P** [comment] 2021-07-29 19:18
Hello @tmaheedhar2. You cannot fetch the image because it does not exist. A search on dockerhub for the image "spe:0.1" does not yield any results: https://hub.docker.com/search?q=spe%3A01&type=image. 

You haven't provided much information about the context of your inquiry, but there are typically two scenarios in which a user might add an image:

### Scenario 1: adding an image from a docker registry
* If using a private registry that requires authentication, please refer to the documentation for [anchore-cli registry add](https://engine.anchore.io/docs/usage/cli_usage/registries/configuring_registries/) first. 
* If you own the image, [please also submit the dockerfile to anchore](https://engine.anchore.io/docs/usage/cli_usage/images/#adding-images-that-you-own) while adding it.

### Scenario 2: adding an image from your docker host to a local anchore deployment
There are currently two approaches that may suit your needs.
#### Approach 1:
* Use the Syft upload feature to perform local analysis / sbom generation and [upload the results](https://github.com/anchore/syft) to anchore.
#### Approach 2:
* Run the docker registry on your local machine and push the image to the registry. Then upload the image to anchore as usual:
  1. Run the registry: `docker run -d -p 5000:5000 --name registry registry:2`
  1. Tag the image to upload to the registry: `docker tag <your image name and tag> localhost:5000/<repo name>:<tag>`
  1. Push the image to the registry: `docker push localhost:5000/<repo name>:<tag>`
  1. Exec into the API container (if using k8s, use kubectl exec instead) `docker-compose exec api anchore-cli image add host.docker.internal:5000/<repo name>:<tag>`

**Comment by Vijay-P** [comment] 2021-07-29 19:20
This issue appears to be user error and not a bug or feature request. Feel free to continue asking questions, but I'm closing the issue.

**Closed by Vijay-P** 2021-07-29 19:20 UTC
Labels: triaged
