### ISSUE TITLE
Anchore-engine doesn't survive restarting database

### ISSUE THREAD

**Issue by pbalogh-sa** [anchore/anchore-engine#116] opened 2018-12-06 11:47 UTC
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**: 0.3.0

 
**What happened**:
If postgres is restarted or connection lost by some reason, authentication will be failed due to anchore-engine don't reconnect to database and it must be restarted.

**What did you expect to happen**:
It would be better if anchore-engine could reconnect to database after lost connection.

**Any relevant log output from /var/log/anchore**:
...
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.common/update_service_cache()] [WARN] cannot get service: [Errno 32] Broken pipe
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.common/update_service_cache()] [WARN] cannot get service: [Errno 32] Broken pipe
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.internal/dispatch()] [ERROR] Failed client call to service simplequeue for url: http://anchore-deployment-anchore-engine:8083/v1/queues/watcher_tasks/is_inqueue. Response: {'httpcode': 401, 'anchore_error_raw': "b'Unauthorized'", 'anchore_error_json': {}}
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.services.catalog/schedule_watcher()] [WARN] failed to enqueue watcher task: failed post url=http://anchore-deployment-anchore-engine:8083/v1/queues/watcher_tasks/is_inqueue
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.common/update_service_cache()] [WARN] cannot get service: [Errno 32] Broken pipe
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.common/update_service_cache()] [WARN] cannot get service: [Errno 32] Broken pipe
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.internal/dispatch()] [ERROR] Failed client call to service simplequeue for url: http://anchore-deployment-anchore-engine:8083/v1/queues/watcher_tasks/is_inqueue. Response: {'httpcode': 401, 'anchore_error_raw': "b'Unauthorized'", 'anchore_error_json': {}}
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.services.catalog/schedule_watcher()] [WARN] failed to enqueue watcher task: failed post url=http://anchore-deployment-anchore-engine:8083/v1/queues/watcher_tasks/is_inqueue
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.common/update_service_cache()] [WARN] cannot get service: [Errno 32] Broken pipe
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.common/update_service_cache()] [WARN] cannot get service: [Errno 32] Broken pipe
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.internal/dispatch()] [ERROR] Failed client call to service simplequeue for url: http://anchore-deployment-anchore-engine:8083/v1/queues/watcher_tasks/is_inqueue. Response: {'httpcode': 401, 'anchore_error_raw': "b'Unauthorized'", 'anchore_error_json': {}}
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.services.catalog/schedule_watcher()] [WARN] failed to enqueue watcher task: failed post url=http://anchore-deployment-anchore-engine:8083/v1/queues/watcher_tasks/is_inqueue
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.common/update_service_cache()] [WARN] cannot get service: [Errno 32] Broken pipe
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.common/update_service_cache()] [WARN] cannot get service: [Errno 32] Broken pipe
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.internal/dispatch()] [ERROR] Failed client call to service simplequeue for url: http://anchore-deployment-anchore-engine:8083/v1/queues/watcher_tasks/is_inqueue. Response: {'httpcode': 500, 'anchore_error_raw': 'b\'"[Errno 32] Broken pipe"\\n\'', 'anchore_error_json': '[Errno 32] Broken pipe'}
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.services.catalog/schedule_watcher()] [WARN] failed to enqueue watcher task: failed post url=http://anchore-deployment-anchore-engine:8083/v1/queues/watcher_tasks/is_inqueue
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.common/update_service_cache()] [WARN] cannot get service: [Errno 32] Broken pipe
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.common/update_service_cache()] [WARN] cannot get service: [Errno 32] Broken pipe
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.internal/dispatch()] [ERROR] Failed client call to service simplequeue for url: http://anchore-deployment-anchore-engine:8083/v1/queues/watcher_tasks/is_inqueue. Response: {'httpcode': 401, 'anchore_error_raw': "b'Unauthorized'", 'anchore_error_json': {}}
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.services.catalog/schedule_watcher()] [WARN] failed to enqueue watcher task: failed post url=http://anchore-deployment-anchore-engine:8083/v1/queues/watcher_tasks/is_inqueue
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.common/update_service_cache()] [WARN] cannot get service: [Errno 32] Broken pipe
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.common/update_service_cache()] [WARN] cannot get service: [Errno 32] Broken pipe
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.internal/dispatch()] [ERROR] Failed client call to service simplequeue for url: http://anchore-deployment-anchore-engine:8083/v1/queues/watcher_tasks/is_inqueue. Response: {'httpcode': 401, 'anchore_error_raw': "b'Unauthorized'", 'anchore_error_json': {}}
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.services.catalog/schedule_watcher()] [WARN] failed to enqueue watcher task: failed post url=http://anchore-deployment-anchore-engine:8083/v1/queues/watcher_tasks/is_inqueue
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.common/update_service_cache()] [WARN] cannot get service: [Errno 32] Broken pipe
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.common/update_service_cache()] [WARN] cannot get service: [Errno 32] Broken pipe
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.internal/dispatch()] [ERROR] Failed client call to service simplequeue for url: http://anchore-deployment-anchore-engine:8083/v1/queues/watcher_tasks/is_inqueue. Response: {'httpcode': 401, 'anchore_error_raw': "b'Unauthorized'", 'anchore_error_json': {}}
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.services.catalog/schedule_watcher()] [WARN] failed to enqueue watcher task: failed post url=http://anchore-deployment-anchore-engine:8083/v1/queues/watcher_tasks/is_inqueue
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.common/update_service_cache()] [WARN] cannot get service: [Errno 32] Broken pipe
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.common/update_service_cache()] [WARN] cannot get service: [Errno 32] Broken pipe
[service:catalog] 2018-12-05 20:38:08+0000 [-] [Thread-569956] [anchore_engine.clients.services.common/update_service_cache()] [WARN] cannot get service: [Errno 32] Broken pipe
[service:simplequeue] 2018-12-05 20:38:08+0000 [-] Traceback (most recent call last):
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/anchore_engine/apis/authorization.py", line 263, in authenticate
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     identity, _ = idp.lookup_user(user)
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/anchore_engine/apis/authentication.py", line 32, in lookup_user
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     usr = self.mgr.get_user(username)
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/anchore_engine/subsys/identities.py", line 234, in get_user
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     return db_account_users.get(username, session=self.session)
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/anchore_engine/db/db_account_users.py", line 114, in get
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     usr = session.query(AccountUser).filter_by(username=username).one_or_none()
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 2924, in one_or_none
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     ret = list(self)
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     return self._execute_and_instances(context)
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3018, in _execute_and_instances
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     result = conn.execute(querycontext.statement, self._params)
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     return meth(self, multiparams, params)
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     return connection._execute_clauseelement(self, multiparams, params)
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     compiled_sql, distilled_params
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     context)
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1416, in _handle_dbapi_exception
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     util.reraise(*exc_info)
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 249, in reraise
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     raise value
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     context)
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 509, in do_execute
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     cursor.execute(statement, parameters)
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/pg8000/core.py", line 891, in execute
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     self._c.execute(self, "begin transaction", None)
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/pg8000/core.py", line 1917, in execute
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     self._send_message(BIND, retval)
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/pg8000/core.py", line 1925, in _send_message
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     self._write(code)
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]   File "/usr/lib/python3.6/socket.py", line 604, in write
[service:simplequeue] 2018-12-05 20:38:08+0000 [-]     return self._sock.send(b)
[service:simplequeue] 2018-12-05 20:38:08+0000 [-] BrokenPipeError: [Errno 32] Broken pipe
...
**What docker images are you using**: v0.3.0

**How to reproduce the issue**:
Restart database backend (kubectl delete anchore-deployment-postgresql-pod)

**Anything else we need to know**:
I run anchore with kubernetes

**Comment by nurmi** [comment] 2018-12-06 22:45
@pbalogh-sa - thank you for this report!  We're investigating the root cause of this behavior, as SQLAlchemy (which anchore uses for DB interactions) connection pool should (and has) be handling pool connection retries.  However, investigations so far are indeed indicating that the current pg8000 driver in sqlalchemy is not behaving as it should in this scenario.

We'll update this ticket as we learn more, including a suggested solution!  So far, we've found that the other PG drivers and older pg8000 drivers are still functioning propely in sql alchemy, handling DB disconnect/reconnect events properly.

**Comment by pbalogh-sa** [comment] 2018-12-17 10:30
@nurmi  thanks for your efforts, I'm waiting for your update.

**Comment by JyothsnaGuduri** [comment] 2019-01-07 21:45
I am seeing same error logs on the anchore startup with Aurora PostgreSQL. I am running anchore service on ECS. Following this post

**Comment by nurmi** [comment] 2019-01-07 21:56
Update on this issue - we have code committed to master (and available for testing in the anchore/anchore-engine:dev container from dockerhub) that

a) reverts the pg8000 driver version to 1.10.6 which handles PG disconnects through SQL Alchemy correctly and

b) includes initial support for changing which PG driver is used by SQL alchemy via anchore-engine configuration (i.e. altering the pg connection string in anchore's config.yaml with a specific driver).  

For the time being, we will still be using / testing with the pg8000 driver by default.  This update will be part of the next release of anchore-engine (v0.3.2), and is testable now in dev environments with the anchore/anchore-engine:dev container

**Comment by pbalogh-sa** [comment] 2019-01-08 07:41
@nurmi - thanks. I've checked it in my test environment and anchore-engine has reconnected successfully.

**Comment by nurmi** [comment] 2019-01-14 20:05
This update (revert to 1.10.6 version of pg8000 driver) has been committed to anchore-engine and released in version of engine 0.3.2.

**Closed by nurmi** 2019-01-14 20:05 UTC
